apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-sample-api
  labels:
    app: java-sample-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-sample-api
  template:
    metadata:
      labels:
        app: java-sample-api
    spec:
      containers:
      - image: nextmetaphor/java-microservice-api
        imagePullPolicy: IfNotPresent
        name: java-sample-api
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 500m