apiVersion: v1
kind: Service
metadata:
  name: java-sample-api
  namespace: demo
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    nodePort: 30080
  selector:
    app: java-sample-api
  type: NodePort