apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: golang-sample-api
  namespace: demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: golang-sample-api
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50


